name: "Setup Environment"
description: "Platform-aware setup - uses Docker on Linux, native on others"
inputs:
  env:
    description: "Environment variables in JSON format"
    required: true
  cache-key:
    description: "Cache key prefix"
    required: true
  docker-image:
    description: "Docker image tag to use"
    required: true
  docker-cache:
    description: "Docker cache registry reference"
    required: true
  github-token:
    description: "GitHub token for authenticated API requests"
    required: true
  docker-service:
    description: "Docker service name"
    required: true
  mise-version:
    description: "Mise version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Restore shared caches"
      uses: "actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7" # v5.0.2
      with:
        path: ".cache/shared"
        key: "${{ inputs.cache-key }}-shared-${{ runner.os }}-${{ runner.arch }}"
    - name: "Setup .env file"
      shell: "bash"
      env:
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        ENV: "${{ inputs.env }}"
      run: |
        printf "GITHUB_TOKEN=%s\n" "$GITHUB_TOKEN" > .env
        printf "%s" "$ENV" | jq -er "to_entries[] | \"\(.key)=\(.value)\"" >> .env
    - name: "Setup (Docker)"
      if: "runner.os == 'Linux'"
      uses: "./.github/actions/setup-docker"
      with:
        cache-key: "${{ inputs.cache-key }}"
        docker-image: "${{ inputs.docker-image }}"
        docker-cache: "${{ inputs.docker-cache }}"
        github-token: "${{ inputs.github-token }}"
        docker-service: "${{ inputs.docker-service }}"
    - name: "Setup (Native)"
      if: "runner.os != 'Linux'"
      uses: "./.github/actions/setup-native"
      with:
        cache-key: "${{ inputs.cache-key }}"
        github-token: "${{ inputs.github-token }}"
        mise-version: "${{ inputs.mise-version }}"
    - name: "Mise setup"
      uses: "./.github/actions/shell"
      with:
        docker-service: "${{ inputs.docker-service }}"
        run: "mise setup"
