name: 'Setup Environment'
description: 'Platform-aware setup - uses Docker on Linux, native on others'

inputs:
  env:
    description: 'Environment variables in JSON format'
    required: true
  pnpm-version:
    description: 'Version of pnpm to install'
    required: true
  node-version:
    description: 'Version of Node.js to install'
    required: true
  docker-image:
    description: 'Docker image tag to use'
    required: true
  docker-cache:
    description: 'Docker cache registry reference'
    required: true
  github-token:
    description: 'GitHub token for authenticated API requests'
    required: true
  docker-user:
    description: 'Docker container user'
    required: true
  docker-workspace:
    description: 'Docker container workspace folder'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Restore uv cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ~/.cache/uv
        key: uv-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ runner.arch }}-

    - name: Restore pnpm cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-${{ runner.arch }}-

    - name: Restore cargo binaries
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: .bin
        key: cargo-bin-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          cargo-bin-${{ runner.os }}-${{ runner.arch }}-
    
    - name: Restore sccache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ${{ fromJSON(inputs.env).SCCACHE_DIR }}
        key: sccache-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
        restore-keys: |
          sccache-${{ runner.os }}-${{ runner.arch }}-

    - name: Restore cargo target
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: target
        key: cargo-target-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-target-${{ runner.os }}-${{ runner.arch }}-

    - name: Setup (Docker)
      if: runner.os == 'Linux'
      uses: ./.github/actions/setup-docker
      with:
        env: ${{ inputs.env }}
        docker-image: ${{ inputs.docker-image }}
        docker-cache: ${{ inputs.docker-cache }}
        github-token: ${{ inputs.github-token }}
        docker-user: ${{ inputs.docker-user }}
        docker-workspace: ${{ inputs.docker-workspace }}

    - name: Setup (Native)
      if: runner.os != 'Linux'
      uses: ./.github/actions/setup-native
      with:
        env: ${{ inputs.env }}
        pnpm-version: ${{ inputs.pnpm-version }}
        node-version: ${{ inputs.node-version }}
        github-token: ${{ inputs.github-token }}
