coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true

ignore:
  - "**/scripts/**/*"
  - "**/tests/**/*"
