packages:
  - packages/core
  - packages/meta
  - packages/node

allowBuilds:
  better-sqlite3: true
  core-js-pure: true
  dtrace-provider: true
  electron: true
  esbuild: true
  node-pty: true
  protobufjs: true
  re2: true
  tree-sitter-bash: true

blockExoticSubdeps: true

catalog:
  "@codecov/vite-plugin": ^1.9.1
  "@google/gemini-cli": ^0.24.5
  "@mapbox/node-pre-gyp": ^2.0.3
  "@playwright/test": 1.57.0
  "@rollup/plugin-node-resolve": ^16.0.3
  "@taplo/cli": ^0.7.0
  "@types/node": ^24.10.9
  "@vitest/coverage-istanbul": ^4.0.17
  electron: ^40.0.0
  hono: ^4.11.4
  husky: ^9.1.7
  markdownlint-cli2: ^0.20.0
  monocart-reporter: ^2.9.23
  renovate: ^42.86.0
  rollup-plugin-node-externals: ^8.1.2
  rollup: ^4.55.2
  fd-lock: ^2.1.1
  typescript: ^5.9.3
  undici: ^7.18.2
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.17

minimumReleaseAge: 1440

strictDepBuilds: true
