packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.8
  '@codecov/vite-plugin': ^1.9.1
  '@mapbox/node-pre-gyp': ^2.0.3
  '@playwright/test': 1.57.0
  '@rollup/plugin-node-resolve': ^16.0.3
  '@taplo/cli': ^0.7.0
  '@types/node': ^22.19.3
  '@vitest/coverage-istanbul': &vitest ^4.0.16
  cargo-cp-artifact: ^0.1.9
  electron: ^39.2.7
  husky: ^9.1.7
  markdownlint-cli2: ^0.20.0
  monocart-reporter: ^2.9.23
  rollup-plugin-node-externals: ^8.1.2
  typescript: ^5.9.3
  undici: ^7.16.0
  vite: ^7.2.7
  vite-plugin-dts: ^4.5.4
  vitest: *vitest

strictDepBuilds: true
allowBuilds:
  esbuild: true
  electron: true

minimumReleaseAge: 10080 # 7 days (synced with dependabot cooldown)
minimumReleaseAgeExclude: null
trustPolicy: no-downgrade
trustPolicyExclude: null
blockExoticSubdeps: true
