packages:
  - packages/core
  - packages/meta
  - packages/node

blockExoticSubdeps: true

catalog:
  '@codecov/vite-plugin': 1.9.1
  '@playwright/test': 1.58.2
  '@rollup/plugin-node-resolve': 16.0.3
  '@sigstore/bundle': 4.0.0
  '@sigstore/core': 3.1.0
  '@sigstore/rekor-types': 4.0.0
  '@taplo/cli': 0.7.0
  '@types/node': 24.10.15
  '@vitest/coverage-istanbul': 4.0.18
  electron: 40.6.1
  fd-lock: 2.1.1
  husky: 9.1.7
  markdownlint-cli2: 0.20.0
  monocart-reporter: 2.10.0
  oxfmt: 0.32.0
  oxlint: 1.50.0
  rollup: 4.59.0
  rollup-plugin-node-externals: 8.1.2
  sigstore: 4.1.0
  typescript: 5.9.3
  undici: 7.22.0
  vite: 7.3.1
  vite-plugin-dts: 4.5.4
  vitest: 4.0.18

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - electron
  - esbuild

overrides:
  undici@<6.23.0: '>=6.23.0'

strictDepBuilds: true
