packages:
  - packages/core
  - packages/meta
  - packages/node

blockExoticSubdeps: true

catalog:
  '@codecov/vite-plugin': 1.9.1
  '@playwright/test': 1.58.2
  '@taplo/cli': 0.7.0
  '@types/node': 24.12.0
  '@vitest/coverage-istanbul': 4.1.1
  electron: 40.8.3
  fd-lock: 2.1.1
  husky: 9.1.7
  markdownlint-cli2: 0.22.0
  monocart-reporter: 2.10.0
  oxfmt: 0.41.0
  oxlint: 1.56.0
  typescript: 6.0.2
  undici: 7.24.5
  vite: 8.0.2
  vite-plugin-dts: 5.0.0-beta.6
  vitest: 4.1.1

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - node-addon-slsa

onlyBuiltDependencies:
  - electron
  - esbuild
  - node-addon-slsa

overrides:
  undici@<6.23.0: '>=6.23.0'

strictDepBuilds: true
