packages:
  - packages/core
  - packages/meta
  - packages/node

blockExoticSubdeps: true

catalog:
  "@codecov/vite-plugin": ^1.9.1
  "@playwright/test": 1.58.0
  "@rollup/plugin-node-resolve": ^16.0.3
  "@taplo/cli": ^0.7.0
  "@types/node": ^24.10.9
  "@vitest/coverage-istanbul": ^4.0.18
  electron: ^40.1.0
  fd-lock: ^2.1.1
  husky: ^9.1.7
  markdownlint-cli2: ^0.20.0
  monocart-reporter: ^2.9.23
  oxfmt: ^0.34.0
  oxlint: ^1.41.0
  rollup: ^4.57.1
  rollup-plugin-node-externals: ^8.1.2
  typescript: ^5.9.3
  undici: ^7.19.2
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.18

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - electron
  - esbuild

overrides:
  undici@<6.23.0: ">=6.23.0"

strictDepBuilds: true
