name: 'Platform shell'
description: 'Run shell commands in Bash or MSVC powershell'

inputs:
  run:
    description: 'The command to run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run command (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: ${{ inputs.run }}
    
    - name: Run command (Linux)
      if: runner.os == 'Linux'
      shell: bash
      env:
        INPUT_SCRIPT: ${{ inputs.run }}
      run: |
        SCRIPT_PATH=$(mktemp)
        echo "$INPUT_SCRIPT" > "$SCRIPT_PATH"
        chmod +x "$SCRIPT_PATH"
        xvfb-run --auto-servernum -- "$SCRIPT_PATH"
    
    - name: Run command (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: ${{ inputs.run }}
