name: 'Setup Agent Environment'
description: 'Sets up the development environment with Node.js and Rust'

inputs:
  env:
    description: 'Additional environment variables in JSON format'
    required: true
  pnpm-version:
    description: 'Version of pnpm to install'
    required: true
  node-version:
    description: 'Version of Node.js to install'
    required: true
  github-token:
    description: 'GitHub token for authenticated API requests (increases rate limits)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      env:
        ENV: ${{ inputs.env }}
      run: echo "$ENV" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> "$GITHUB_ENV"
    
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: ${{ inputs.pnpm-version }}
    
    - name: Install Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install UV
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        enable-cache: true
    
    - name: Setup MSVC developer command prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      with:
        cache-directories: |
          .bin
          ~/.cargo/bin
    
    - name: Install Cargo binstall
      uses: cargo-bins/cargo-binstall@8110b3aa84cb581a90696bc57469b0656f972494 # v1.16.3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    
    - name: Run pnpm install script
      uses: ./.github/actions/platform-shell
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        run: |
          pnpm install --frozen-lockfile --prefer-offline
