name: 'Setup Agent Environment'
description: 'Sets up the development environment with Node.js and Rust'

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "HUSKY=0" >> "$GITHUB_ENV"
        echo "CARGO_INCREMENTAL=0" >> "$GITHUB_ENV"
        echo "RUST_BACKTRACE=1" >> "$GITHUB_ENV"
    
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: '10.24.0'

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-store-dir
      run: echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
    
    - name: Restore pnpm cache
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
      with:
        path: |
          ~/.pnpm-store
          ${{ steps.pnpm-store-dir.outputs.dir }}
        key: ${{ runner.os }}-${{ runner.arch }}-pnpm-v0-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-pnpm-v0-
    
    - name: Setup MSVC developer command prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      with:
        toolchain: 'nightly'
        components: 'clippy, rustfmt'
    
    - name: Restore Rust cache
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ runner.arch }}-rust-v0-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-rust-v0-
    
    - name: Install Cargo binstall
      uses: cargo-bins/cargo-binstall@8110b3aa84cb581a90696bc57469b0656f972494 # v1.16.3
    
    - name: Run pnpm install script
      uses: ./.github/actions/platform-shell
      with:
        run: |
          pnpm install --frozen-lockfile --prefer-offline

    - name: Install Playwright dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: pnpm exec playwright install-deps
