name: 'Setup Agent Environment'
description: 'Sets up the development environment with Node.js and Rust'

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "HUSKY=0" >> "$GITHUB_ENV"
        echo "CARGO_INCREMENTAL=0" >> "$GITHUB_ENV"
        echo "RUST_BACKTRACE=1" >> "$GITHUB_ENV"
    
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: '10.24.0'
    
    - name: Install Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: '22.19.0'
        cache: 'pnpm'
    
    - name: Setup MSVC developer command prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      with:
        toolchain: 'nightly'
        components: 'clippy, rustfmt'
        cache-directories: |
          .bin
    
    - name: Install Cargo binstall
      uses: cargo-bins/cargo-binstall@8110b3aa84cb581a90696bc57469b0656f972494 # v1.16.3
    
    - name: Run pnpm install script
      uses: ./.github/actions/platform-shell
      with:
        run: |
          pnpm install --frozen-lockfile --prefer-offline
