name: 'Shell (Docker)'
description: 'Run commands inside the devcontainer'
inputs:
  run:
    description: 'Commands to run'
    required: true
  docker-service:
    description: 'Docker service name'
    required: true
  github-token:
    description: 'GitHub token for authenticated API requests (increases rate limits)'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Run in container
      shell: bash
      env:
        INPUT_RUN: ${{ inputs.run }}
        DOCKER_SERVICE: ${{ inputs.docker-service }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        printf "%s" "$INPUT_RUN" | \
          docker compose exec -T -e GITHUB_TOKEN "$DOCKER_SERVICE" bash
