name: "Shell (Docker)"
description: "Run commands inside the devcontainer"
inputs:
  run:
    description: "Commands to run"
    required: true
  docker-service:
    description: "Docker service name"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run in container"
      shell: "bash"
      env:
        INPUT_RUN: "${{ inputs.run }}"
        DOCKER_SERVICE: "${{ inputs.docker-service }}"
        COMPOSE_FILE: "docker-compose.yml:docker-compose.override.yml"
      run: |
        printf "%s" "$INPUT_RUN" | \
          docker compose exec -T "$DOCKER_SERVICE" bash
