name: 'Shell (Docker)'
description: 'Run commands inside the devcontainer'

inputs:
  run:
    description: 'Commands to run'
    required: true
  docker-container:
    description: 'Docker container name'
    default: 'devcontainer'

runs:
  using: 'composite'
  steps:
    - name: Run in container
      shell: bash
      env:
        INPUT_RUN: ${{ inputs.run }}
        CONTAINER_NAME: ${{ inputs.docker-container }}
      run: |
        docker exec "$CONTAINER_NAME" bash -c "$INPUT_RUN"
