name: 'Init Workflow'
description: 'Defines central configurations and constants for workflows'

outputs:
  matrix:
    description: 'Matrix for regular runs'
    value: |
      {
        "os": [
          "ubuntu-24.04",
          "ubuntu-24.04-arm",
          "macos-15-intel",
          "macos-15",
          "windows-2025",
          "windows-11-arm"
        ]
      }
  cache-key:
    description: 'Cache key prefix for manual invalidation'
    value: 'v0'
  env:
    description: 'Environment variables'
    value: |
      {
        "CI": "true",
        "HUSKY": "0",
        "CARGO_INCREMENTAL": "0",
        "CARGO_NET_GIT_FETCH_WITH_CLI": "true",
        "RUST_BACKTRACE": "1",
        "RUSTC_WRAPPER": "sccache",
        "SCCACHE_CACHE_SIZE": "5G"
      }
  pnpm-version:
    description: 'pnpm version'
    value: ${{ steps.parse.outputs.pnpm-version }}
  node-version:
    description: 'Node.js version'
    value: ${{ steps.parse.outputs.node-version }}
  test-coverage:
    description: 'Globs for coverage reports'
    value: 'packages/**/lcov.info'
  test-reports:
    description: 'Globs for test reports'
    value: 'packages/**/report-*.junit.xml'
  docker-image:
    description: 'Docker image tag'
    value: ${{ steps.parse.outputs.docker-image }}
  docker-service:
    description: 'Docker service name'
    value: ${{ steps.parse.outputs.docker-service }}
  docker-cache:
    description: 'Docker cache registry reference'
    value: ${{ steps.parse.outputs.docker-cache }}

runs:
  using: 'composite'
  steps:
    - name: Parse versions from package.json
      id: parse
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        PNPM_VERSION=$(jq -er '.engines.pnpm | ltrimstr("^")' package.json)
        NODE_VERSION=$(jq -er '.engines.node | ltrimstr("^")' package.json)
        
        REPO_NAME=$(basename "$GITHUB_REPOSITORY")
        DOCKER_SERVICE=$(yq -er '.services | keys | .[0]' docker-compose.yml)
        DOCKER_IMAGE="${REPO_NAME}-${DOCKER_SERVICE}"
        DOCKER_CACHE=$(yq -er ".services[\"$DOCKER_SERVICE\"].build.cache_from[0]" docker-compose.yml)
        
        echo "pnpm-version=$PNPM_VERSION" >> "$GITHUB_OUTPUT"
        echo "node-version=$NODE_VERSION" >> "$GITHUB_OUTPUT"
        echo "docker-image=$DOCKER_IMAGE" >> "$GITHUB_OUTPUT"
        echo "docker-service=$DOCKER_SERVICE" >> "$GITHUB_OUTPUT"
        echo "docker-cache=$DOCKER_CACHE" >> "$GITHUB_OUTPUT"
