name: "Init Workflow"
description: "Defines central configurations and constants for workflows"
outputs:
  matrix:
    description: "Matrix for regular runs"
    value: |
      {
        "os": [
          "ubuntu-24.04",
          "ubuntu-24.04-arm",
          "macos-15-intel",
          "macos-15",
          "windows-2025",
          "windows-11-arm"
        ]
      }
  cache-key:
    description: "Cache key prefix for manual invalidation"
    value: "v17"
  env:
    description: "Environment variables"
    value: |
      {
        "CI": "true",
        "CARGO_INCREMENTAL": "0",
        "CARGO_NET_GIT_FETCH_WITH_CLI": "true",
        "RUST_BACKTRACE": "1"
      }
  test-coverage:
    description: "Globs for coverage reports"
    value: "packages/**/lcov.info"
  test-reports:
    description: "Globs for test reports"
    value: "packages/**/report-*.junit.xml"
  docker-image:
    description: "Docker image tag"
    value: "${{ steps.parse.outputs.docker-image }}"
  docker-service:
    description: "Docker service name"
    value: "${{ steps.parse.outputs.docker-service }}"
  docker-cache:
    description: "Docker cache registry reference"
    value: "${{ steps.parse.outputs.docker-cache }}"
runs:
  using: "composite"
  steps:
    - name: "Parse versions from mise.toml"
      id: "parse"
      shell: "bash"
      env:
        GITHUB_REPOSITORY: "${{ github.repository }}"
      run: |
        REPO_NAME=$(basename "$GITHUB_REPOSITORY")
        DOCKER_SERVICE=$(yq -er '.services | keys | .[0]' docker-compose.yml)
        DOCKER_IMAGE="${REPO_NAME}-${DOCKER_SERVICE}"
        DOCKER_CACHE=$(yq -er ".services[\"$DOCKER_SERVICE\"].build.cache_from[0]" docker-compose.yml | sed 's/.*ref=\([^,]*\).*/\1/')

        echo "docker-image=$DOCKER_IMAGE" >> "$GITHUB_OUTPUT"
        echo "docker-service=$DOCKER_SERVICE" >> "$GITHUB_OUTPUT"
        echo "docker-cache=$DOCKER_CACHE" >> "$GITHUB_OUTPUT"
