name: "Shell (Native)"
description: "Run shell commands in Bash or MSVC powershell"
inputs:
  run:
    description: "The command to run"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run command (Unix)"
      if: "runner.os != 'Windows'"
      shell: "bash"
      env:
        INPUT_SCRIPT: "${{ inputs.run }}"
      run: |
        eval "$(mise activate bash)"
        eval "$INPUT_SCRIPT"
    - name: "Run command (Windows)"
      if: "runner.os == 'Windows'"
      shell: "pwsh"
      env:
        INPUT_SCRIPT: "${{ inputs.run }}"
      run: |
        (&mise activate pwsh) | Out-String | Invoke-Expression
        Invoke-Expression $env:INPUT_SCRIPT
