name: 'Setup (Docker)'
description: 'Build container image locally, warm registry cache'

inputs:
  env:
    description: 'Environment variables in JSON format'
    required: true
  docker-image:
    description: 'Docker image tag to use'
    required: true
  docker-cache:
    description: 'Docker cache registry reference'
    required: true
  github-token:
    description: 'GitHub token for registry authentication'
    required: true
  docker-user:
    description: 'Docker container user'
    required: true
  docker-workspace:
    description: 'Docker container workspace'
    required: true
  docker-container:
    description: 'Docker container name'
    default: 'devcontainer'

runs:
  using: 'composite'
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Setup Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Get current UID/GID
      id: ids
      shell: bash
      run: |
        echo "uid=$(id -u)" >> "$GITHUB_OUTPUT"
        echo "gid=$(id -g)" >> "$GITHUB_OUTPUT"

    - name: Build Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        file: .devcontainer/Dockerfile
        platforms: ${{ runner.arch == 'ARM64' && 'linux/arm64' || 'linux/amd64' }}
        load: true
        tags: ${{ inputs.docker-image }}
        cache-from: type=registry,ref=${{ inputs.docker-cache }}
        cache-to: type=registry,ref=${{ inputs.docker-cache }},mode=max,image-manifest=true
        build-args: |
          USER_UID=${{ steps.ids.outputs.uid }}
          USER_GID=${{ steps.ids.outputs.gid }}
    
    - name: Create host cache directories
      shell: bash
      run: mkdir -p "$HOME/.cache/uv" "$HOME/.pnpm-store" "$HOME/.cache/sccache"

    - name: Start persistent container
      uses: ./.github/actions/docker-lifecycle
      with:
        env: ${{ inputs.env }}
        name: ${{ inputs.docker-container }}
        image: ${{ inputs.docker-image }}
        user: ${{ inputs.docker-user }}
        workspace: ${{ inputs.docker-workspace }}

    - name: Run pnpm install script
      uses: ./.github/actions/shell-docker
      with:
        docker-container: ${{ inputs.docker-container }}
        run: pnpm install --frozen-lockfile --prefer-offline
