name: 'Sign and Notarize Binary'
description: 'Code sign and notarize binaries on macOS and Windows'
inputs:
  binary-path:
    description: 'Path to the binary file to sign'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Sign and notarize stub
      shell: bash
      env:
        BINARY_PATH: ${{ inputs.binary-path }}
      run: echo "TODO: Implement sign and notarize for $BINARY_PATH"
