name: "Setup (Native)"
description: "Sets up the development environment with Node.js and Rust"
inputs:
  env:
    description: "Additional environment variables in JSON format"
    required: true
  cache-key:
    description: "Cache key prefix"
    required: true
  github-token:
    description: "GitHub token for authenticated API requests (increases rate limits)"
    required: true
  mise-version:
    description: "Mise version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Restore native caches"
      uses: "actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7" # v5.0.2
      with:
        path: ".cache/native"
        key: "${{ inputs.cache-key }}-native-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Cargo.lock', 'pyproject.toml', 'pnpm-lock.yaml', 'uv.lock') }}"
        restore-keys: |
          ${{ inputs.cache-key }}-native-${{ runner.os }}-${{ runner.arch }}-
    - name: "Update apt index"
      if: "runner.os == 'Linux'"
      shell: "bash"
      run: "sudo apt-get update"
    - name: "Set environment variables"
      shell: "bash"
      env:
        ENV: "${{ inputs.env }}"
      run: | # zizmor: ignore[github-env]
        printf "%s" "$ENV" | jq -er "to_entries[] | \"\(.key)=\(.value)\"" >> "$GITHUB_ENV"
    - name: "Setup MSVC developer command prompt"
      if: "runner.os == 'Windows'"
      uses: "ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756" # v1.13.0
    - name: "Run mise install"
      uses: "jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8" # v3.6.1
      with:
        version: "${{ inputs.mise-version }}"
        cache_key_prefix: "${{ inputs.cache-key }}-mise"
        github_token: "${{ inputs.github-token }}"
