name: "Setup (Native)"
description: "Sets up the development environment with Node.js and Rust"
inputs:
  env:
    description: "Additional environment variables in JSON format"
    required: true
  cache-key:
    description: "Cache key prefix"
    required: true
  github-token:
    description: "GitHub token for authenticated API requests (increases rate limits)"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Restore native caches"
      uses: "actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb" # v5.0.1
      with:
        path: |
          .cache/native
          ~/.local/share/mise
        key: "${{ inputs.cache-key }}-native-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('mise.toml', 'Cargo.lock', 'pyproject.toml', 'pnpm-lock.yaml', 'uv.lock') }}"
        restore-keys: |
          ${{ inputs.cache-key }}-native-${{ runner.os }}-${{ runner.arch }}-
    - name: "Update apt index"
      if: "runner.os == 'Linux'"
      shell: "bash"
      run: "sudo apt-get update"
    - name: "Set environment variables"
      shell: "bash"
      env:
        ENV: "${{ inputs.env }}"
      run: | # zizmor: ignore[github-env]
        printf "%s" "$ENV" | jq -er "to_entries[] | \"\(.key)=\(.value)\"" >> "$GITHUB_ENV"
    - name: "Setup MSVC developer command prompt"
      if: "runner.os == 'Windows'"
      uses: "ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756" # v1.13.0
    - name: "Install tools via mise"
      uses: "jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5" # v3.5.1
      with:
        install: true
        cache: false
      env:
        GITHUB_TOKEN: "${{ inputs.github-token }}"
