name: 'Shell'
description: 'Platform-aware shell - uses Docker on Linux, native on others'

inputs:
  run:
    description: 'Commands to run'
    required: true
  docker-container:
    description: 'Docker container name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run (Docker)
      if: runner.os == 'Linux'
      uses: ./.github/actions/shell-docker
      with:
        run: ${{ inputs.run }}
        docker-container: ${{ inputs.docker-container }}

    - name: Run (Native)
      if: runner.os != 'Linux'
      uses: ./.github/actions/shell-native
      with:
        run: ${{ inputs.run }}
